
(function(){
  const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const clone=o=>JSON.parse(JSON.stringify(o)),deepMerge=(base,value)=>{if(Array.isArray(base))return Array.isArray(value)?value:base;if(base&&typeof base==='object'){const out={...base};if(value&&typeof value==='object')Object.keys(value).forEach(k=>out[k]=k in base?deepMerge(base[k],value[k]):value[k]);return out}return value===undefined?base:value};
  let data=clone(window.DEFAULT_SITE_CONTENT),dirty=false,currentDirection='school',currentSub='albums',captchaToken='',captchaWidgetId=null,lockTimer=null;
  const asset=u=>{if(!u)return '';const v=String(u).trim();if(/^https?:\/\//i.test(v))return v;if(/^assets\//i.test(v))return '../'+v.replace(/^\.\//,'');return ''};
  const uid=p=>`${p}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;
  function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2400)}
  function markDirty(){dirty=true;$('#savebar').classList.remove('hidden')}
  function clean(){dirty=false;$('#savebar').classList.add('hidden')}
  function bindInputs(root=document){$$('[data-path]',root).forEach(el=>{el.addEventListener('input',()=>{setPath(el.dataset.path,el.type==='number'?Number(el.value):el.value);markDirty()});el.addEventListener('change',()=>{setPath(el.dataset.path,el.type==='number'?Number(el.value):el.value);markDirty()})})}
  function setPath(path,value){const a=path.split('.');let x=data;for(let i=0;i<a.length-1;i++)x=x[a[i]];x[a.at(-1)]=value}
  function field(label,path,value,type='text',extra=''){return `<div class="field"><label>${label}</label>${type==='textarea'?`<textarea data-path="${path}" ${extra}>${esc(value)}</textarea>`:`<input data-path="${path}" type="${type}" value="${esc(value)}" ${extra}>`}</div>`}
  function imagePreview(url,tall=false){return `<div class="thumb ${tall?'tall':''}">${url?`<img src="${esc(asset(url))}" alt="Предпросмотр">`:''}</div>`}
  function uploadField(label,action,multiple=false){return `<div class="upload-box"><div class="muted" style="margin-bottom:8px">${label}</div><input type="file" accept="image/*" ${multiple?'multiple':''} data-upload="${action}"></div>`}
  function renderGeneral(){const p=$('#panel-general');p.innerHTML=`<h2>Главная страница</h2><div class="card"><h3>Бренд и слоган</h3>${field('Верхняя строка','brandTop',data.brandTop)}${field('Нижняя строка','brandBottom',data.brandBottom)}${field('Фраза на главной','homeSlogan',data.homeSlogan,'textarea')}</div><div class="card"><h3>Ссылки</h3>${field('Клипы VK','videoUrl',data.videoUrl,'url')}</div><p class="muted">Ссылки на админку на основном сайте отсутствуют. Адрес админки открывается вручную: <code>/admin/</code>.</p>`;bindInputs(p)}
  function renderDirectionButtons(){return `<div class="section-select"><button data-dir="school" class="${currentDirection==='school'?'active':''}">Начальная школа</button><button data-dir="kindergarten" class="${currentDirection==='kindergarten'?'active':''}">Детский сад</button></div><div class="section-select">${[['albums','Альбомы'],['preparation','Подготовка'],['process','Процесс'],['questions','Вопросы'],['photos','Фото']].map(([id,t])=>`<button data-sub="${id}" class="${currentSub===id?'active':''}">${t}</button>`).join('')}</div>`}
  function renderDirections(){const p=$('#panel-directions'),d=data.directions[currentDirection];let body=`<h2>Школа и детский сад</h2>${renderDirectionButtons()}<div class="card"><h3>Общие настройки направления</h3><div class="grid-2"><div>${field('Название',`directions.${currentDirection}.title`,d.title)}${field('Подзаголовок',`directions.${currentDirection}.subtitle`,d.subtitle,'textarea')}</div><div>${imagePreview(d.hero)}${uploadField('Заменить главное фото','direction-hero')}</div></div></div>`;if(currentSub==='albums')body+=albumsEditor(d);if(currentSub==='preparation'||currentSub==='process')body+=textEditor(d,currentSub);if(currentSub==='questions')body+=faqEditor(d);if(currentSub==='photos')body+=photosEditor(d);p.innerHTML=body;bindInputs(p);bindDirectionActions(p)}
  function albumsEditor(d){return `<div class="card"><div class="item-head"><h3 style="margin:0;flex:1">Виды альбомов</h3><button class="btn small" data-action="add-album">Добавить альбом</button></div><div class="item-list">${d.albums.map((a,i)=>`<article class="item" data-album-index="${i}"><div class="item-head"><strong>${esc(a.title||'Без названия')}</strong><button class="btn small danger" data-action="delete-album" data-index="${i}">Удалить</button></div><div class="grid-2"><div>${field('Название',`directions.${currentDirection}.albums.${i}.title`,a.title)}${field('Подпись',`directions.${currentDirection}.albums.${i}.subtitle`,a.subtitle)}${field('Свободный текст',`directions.${currentDirection}.albums.${i}.text`,a.text,'textarea')}</div><div>${imagePreview(a.cover)}${uploadField('Заменить обложку',`album-cover:${i}`)}</div></div><h4>Фотографии альбома</h4>${imageList(a.gallery||[],`album-gallery:${i}`)}${uploadField('Добавить фотографии',`album-gallery-add:${i}`,true)}</article>`).join('')}</div></div>`}
  function textEditor(d,k){const s=d[k];return `<div class="card"><h3>${k==='preparation'?'Подготовка':'Процесс'}</h3>${field('Заголовок',`directions.${currentDirection}.${k}.title`,s.title)}${field('Вступление',`directions.${currentDirection}.${k}.intro`,s.intro,'textarea')}${field('Основной текст',`directions.${currentDirection}.${k}.body`,s.body,'textarea','style="min-height:260px"')}</div>`}
  function faqEditor(d){const s=d.questions;return `<div class="card"><h3>Настройки раздела</h3>${field('Заголовок',`directions.${currentDirection}.questions.title`,s.title)}${field('Вступление',`directions.${currentDirection}.questions.intro`,s.intro,'textarea')}</div><div class="card"><div class="item-head"><h3 style="margin:0;flex:1">Вопросы и ответы</h3><button class="btn small" data-action="add-faq">Добавить вопрос</button></div><div class="item-list">${(s.items||[]).map((q,i)=>`<article class="item"><div class="item-head"><strong>Вопрос ${i+1}</strong><button class="btn small" data-action="move-faq" data-index="${i}" data-delta="-1">↑</button><button class="btn small" data-action="move-faq" data-index="${i}" data-delta="1">↓</button><button class="btn small danger" data-action="delete-faq" data-index="${i}">Удалить</button></div>${field('Вопрос',`directions.${currentDirection}.questions.items.${i}.question`,q.question,'textarea')}${field('Ответ',`directions.${currentDirection}.questions.items.${i}.answer`,q.answer,'textarea')}</article>`).join('')}</div></div>`}
  function photosEditor(d){return `<div class="card"><div class="item-head"><h3 style="margin:0;flex:1">Подпапки фотографий</h3><button class="btn small" data-action="add-folder">Добавить подпапку</button></div><div class="item-list">${(d.photoFolders||[]).map((f,i)=>`<article class="item"><div class="item-head"><strong>${esc(f.title)}</strong><button class="btn small danger" data-action="delete-folder" data-index="${i}">Удалить</button></div>${field('Название подпапки',`directions.${currentDirection}.photoFolders.${i}.title`,f.title)}${imageList(f.images||[],`folder-images:${i}`)}${uploadField('Добавить фотографии в подпапку',`folder-images-add:${i}`,true)}</article>`).join('')}</div></div>`}
  function imageList(list,scope){return list.length?`<div class="image-list">${list.map((u,i)=>`<div class="image-item"><img src="${esc(asset(u))}" alt="Фото"><button data-action="delete-image" data-scope="${scope}" data-index="${i}" aria-label="Удалить">×</button></div>`).join('')}</div>`:`<p class="muted">Фотографий пока нет.</p>`}
  function bindDirectionActions(p){$$('[data-dir]',p).forEach(b=>b.onclick=()=>{currentDirection=b.dataset.dir;renderDirections()});$$('[data-sub]',p).forEach(b=>b.onclick=()=>{currentSub=b.dataset.sub;renderDirections()});$$('[data-action]',p).forEach(b=>b.onclick=()=>handleAction(b));$$('[data-upload]',p).forEach(inp=>inp.onchange=()=>handleUpload(inp));}
  async function handleAction(b){const d=data.directions[currentDirection],i=Number(b.dataset.index);if(b.dataset.action==='add-album')d.albums.push({id:uid(currentDirection),title:'Новый альбом',subtitle:'',text:'',cover:d.hero,gallery:[]});if(b.dataset.action==='delete-album'&&confirm('Удалить альбом?'))d.albums.splice(i,1);if(b.dataset.action==='add-faq')d.questions.items.push({question:'Новый вопрос',answer:''});if(b.dataset.action==='delete-faq')d.questions.items.splice(i,1);if(b.dataset.action==='move-faq'){const ni=i+Number(b.dataset.delta);if(ni>=0&&ni<d.questions.items.length)[d.questions.items[i],d.questions.items[ni]]=[d.questions.items[ni],d.questions.items[i]]}if(b.dataset.action==='add-folder')d.photoFolders.push({id:uid(currentDirection+'-photos'),title:'Новая подпапка',images:[]});if(b.dataset.action==='delete-folder'&&confirm('Удалить подпапку и ссылки на фотографии?'))d.photoFolders.splice(i,1);if(b.dataset.action==='delete-image'){const [scope,idx]=b.dataset.scope.split(':');let arr=scope==='album-gallery'?d.albums[Number(idx)].gallery:d.photoFolders[Number(idx)].images;const old=arr[Number(b.dataset.index)];arr.splice(Number(b.dataset.index),1);try{await SiteBackend.deleteImage(old)}catch(e){console.warn(e)}}markDirty();renderDirections()}
  async function handleUpload(inp){const files=[...inp.files];if(!files.length)return;inp.disabled=true;toast('Загрузка…');try{const a=inp.dataset.upload.split(':'),d=data.directions[currentDirection];if(a[0]==='direction-hero'){const url=await SiteBackend.uploadImage(files[0],`${currentDirection}/hero`);d.hero=url}if(a[0]==='album-cover'){const url=await SiteBackend.uploadImage(files[0],`${currentDirection}/albums/${d.albums[Number(a[1])].id}`);d.albums[Number(a[1])].cover=url}if(a[0]==='album-gallery-add'){for(const f of files)d.albums[Number(a[1])].gallery.push(await SiteBackend.uploadImage(f,`${currentDirection}/albums/${d.albums[Number(a[1])].id}/gallery`))}if(a[0]==='folder-images-add'){for(const f of files)d.photoFolders[Number(a[1])].images.push(await SiteBackend.uploadImage(f,`${currentDirection}/photos/${d.photoFolders[Number(a[1])].id}`))}markDirty();renderDirections();toast('Фотографии загружены')}catch(e){toast('Ошибка загрузки: '+e.message)}finally{inp.disabled=false}}
  function renderAbout(){const p=$('#panel-about'),a=data.about;p.innerHTML=`<h2>Обо мне</h2><div class="card">${field('Заголовок','about.title',a.title)}${field('Текст','about.text',a.text,'textarea','style="min-height:220px"')}${field('Интервал слайд-шоу, секунд','about.slideInterval',a.slideInterval,'number','min="2" max="20"')}</div><div class="card"><h3>Фотографии слайд-шоу</h3>${imageList(a.slides||[],'about-slides:0')}${uploadField('Добавить фотографии',`about-add`,true)}</div>`;bindInputs(p);$$('[data-action]',p).forEach(b=>b.onclick=async()=>{const old=a.slides[Number(b.dataset.index)];a.slides.splice(Number(b.dataset.index),1);try{await SiteBackend.deleteImage(old)}catch(e){}markDirty();renderAbout()});$$('[data-upload]',p).forEach(inp=>inp.onchange=async()=>{try{for(const f of inp.files)a.slides.push(await SiteBackend.uploadImage(f,'about'));markDirty();renderAbout();toast('Фотографии загружены')}catch(e){toast(e.message)}})}
  function renderContacts(){const p=$('#panel-contacts'),c=data.contacts;p.innerHTML=`<h2>Контакты</h2><div class="card">${field('Заголовок','contacts.title',c.title)}${field('Текст','contacts.text',c.text,'textarea')}${field('Ссылка VK','contacts.vk',c.vk,'url')}${field('Ссылка MAX','contacts.max',c.max,'url')}</div>`;bindInputs(p)}
  function renderDesign(){const p=$('#panel-design'),t=data.theme,colors=[['Фон','bg'],['Основной текст','ink'],['Дополнительный текст','muted'],['Линии','line'],['Мягкая подложка','surface'],['Кнопки','button'],['Активная кнопка','active']];p.innerHTML=`<h2>Дизайн и шрифты</h2><div class="card"><h3>Цвета</h3><div class="grid-2">${colors.map(([l,k])=>`<div class="field"><label>${l}</label><div class="color-row"><input data-path="theme.${k}" value="${esc(t[k])}"><input type="color" value="${esc(t[k])}" data-color-sync="theme.${k}"></div></div>`).join('')}</div></div><div class="card"><h3>Шрифты</h3>${field('Основной шрифт','theme.bodyFont',t.bodyFont)}${field('Шрифт заголовков','theme.headingFont',t.headingFont)}<div class="grid-3">${field('Основной размер, px','theme.baseSize',t.baseSize,'number')}${field('Бренд, px','theme.brandSize',t.brandSize,'number')}${field('Меню, px','theme.navSize',t.navSize,'number')}${field('Главный слоган, px','theme.homeTitleSize',t.homeTitleSize,'number')}${field('Название направления, px','theme.directionTitleSize',t.directionTitleSize,'number')}${field('Заголовок страницы, px','theme.pageTitleSize',t.pageTitleSize,'number')}${field('Заголовок раздела, px','theme.sectionTitleSize',t.sectionTitleSize,'number')}${field('Заголовок карточки, px','theme.cardTitleSize',t.cardTitleSize,'number')}${field('Межбуквенный интервал текста, px','theme.bodyLetterSpacing',t.bodyLetterSpacing,'number','step="0.1"')}${field('Межбуквенный интервал заголовков, px','theme.headingLetterSpacing',t.headingLetterSpacing,'number','step="0.1"')}${field('Межбуквенный интервал меню, px','theme.navLetterSpacing',t.navLetterSpacing,'number','step="0.1"')}${field('Межстрочный интервал','theme.lineHeight',t.lineHeight,'number','step="0.05"')}</div></div><p class="muted">Эти значения используются одной системой CSS-переменных и одинаково применяются на десктопе, Android и iOS. На узких экранах меняется только адаптивный масштаб крупных заголовков.</p>`;bindInputs(p);$$('[data-color-sync]',p).forEach(c=>c.oninput=()=>{const text=$(`[data-path="${c.dataset.colorSync}"]`,p);text.value=c.value;text.dispatchEvent(new Event('input',{bubbles:true}))})}

  function statBars(rows,labelKey,valueKey){const max=Math.max(1,...rows.map(x=>Number(x[valueKey])||0));return rows.length?`<div class="stat-bars">${rows.map(x=>{const value=Number(x[valueKey])||0,pct=Math.max(3,Math.round(value/max*100));return `<div class="stat-row"><span title="${esc(x[labelKey])}">${esc(x[labelKey])}</span><div class="stat-track"><i style="width:${pct}%"></i></div><strong>${value}</strong></div>`}).join('')}</div>`:'<p class="muted">Данных пока нет.</p>'}
  async function renderStats(days=30){const p=$('#panel-stats');p.innerHTML=`<h2>Статистика посещений</h2><div class="section-select"><button data-days="7" class="${days===7?'active':''}">7 дней</button><button data-days="30" class="${days===30?'active':''}">30 дней</button><button data-days="90" class="${days===90?'active':''}">90 дней</button></div><div class="card loading-card">Загрузка статистики…</div>`;try{const s=await SiteBackend.getSiteStats(days),daily=s.daily||[],pages=s.pages||[],devices=s.devices||[],refs=s.referrers||[],sec=s.security||{};p.innerHTML=`<h2>Статистика посещений</h2><div class="section-select"><button data-days="7" class="${days===7?'active':''}">7 дней</button><button data-days="30" class="${days===30?'active':''}">30 дней</button><button data-days="90" class="${days===90?'active':''}">90 дней</button></div><div class="stats-grid"><div class="stat-card"><span>Просмотры за период</span><strong>${Number(s.pageviews)||0}</strong></div><div class="stat-card"><span>Сеансы за период</span><strong>${Number(s.sessions)||0}</strong></div><div class="stat-card"><span>Просмотры сегодня</span><strong>${Number(s.today_pageviews)||0}</strong></div><div class="stat-card"><span>Сеансы сегодня</span><strong>${Number(s.today_sessions)||0}</strong></div></div><div class="grid-2"><div class="card"><h3>Динамика по дням</h3>${statBars(daily,'date','pageviews')}</div><div class="card"><h3>Популярные страницы</h3>${statBars(pages,'path','pageviews')}</div><div class="card"><h3>Устройства</h3>${statBars(devices,'device','pageviews')}</div><div class="card"><h3>Источники переходов</h3>${statBars(refs,'referrer','pageviews')}</div></div><div class="card"><h3>Безопасность входа</h3><div class="stats-grid compact"><div class="stat-card"><span>Неудачные входы, 24 часа</span><strong>${Number(sec.failed_24h)||0}</strong></div><div class="stat-card"><span>Локальные блокировки, 24 часа</span><strong>${Number(sec.locked_24h)||0}</strong></div><div class="stat-card"><span>Успешные входы, 7 дней</span><strong>${Number(sec.success_7d)||0}</strong></div></div><p class="muted">Статистика не хранит IP-адреса, пароли, ФИО и другие персональные данные.</p></div>`}catch(e){p.innerHTML=`<h2>Статистика посещений</h2><div class="card"><p class="error">Не удалось загрузить статистику: ${esc(e.message)}</p><p class="muted">Выполните файл <code>supabase/security_analytics_upgrade.sql</code> в SQL Editor.</p></div>`}$$('[data-days]',p).forEach(b=>b.onclick=()=>renderStats(Number(b.dataset.days)))}
  const loginStateKey='lena-admin-login-guard-v1';
  function readLoginState(){try{return JSON.parse(localStorage.getItem(loginStateKey)||'{}')}catch(_){return {}}}
  function writeLoginState(v){try{localStorage.setItem(loginStateKey,JSON.stringify(v))}catch(_){}}
  function lockRemaining(){return Math.max(0,Number(readLoginState().blockedUntil||0)-Date.now())}
  function updateLoginGuard(){const ms=lockRemaining(),button=$('#loginForm button[type="submit"]'),hint=$('#loginGuard');if(!button||!hint)return;if(ms>0){button.disabled=true;hint.textContent=`Слишком много попыток. Повторите через ${Math.ceil(ms/1000)} сек.`}else{button.disabled=false;hint.textContent='После 5 ошибок вход временно блокируется.';clearInterval(lockTimer);lockTimer=null}}
  function registerLoginFailure(){const st=readLoginState(),fails=Number(st.fails||0)+1,level=Number(st.level||0);if(fails>=5){const delays=[30000,120000,600000,1800000],blockedUntil=Date.now()+delays[Math.min(level,delays.length-1)];writeLoginState({fails:0,level:level+1,blockedUntil});SiteBackend.recordSecurityEvent('login_locked');if(!lockTimer)lockTimer=setInterval(updateLoginGuard,1000)}else writeLoginState({fails,level,blockedUntil:0});updateLoginGuard()}
  function clearLoginGuard(){try{localStorage.removeItem(loginStateKey)}catch(_){}clearInterval(lockTimer);lockTimer=null;updateLoginGuard()}
  function resetCaptcha(){captchaToken='';if(window.turnstile&&captchaWidgetId!==null)window.turnstile.reset(captchaWidgetId)}
  function initCaptcha(){const key=String(window.APP_CONFIG?.CAPTCHA_SITE_KEY||'').trim(),wrap=$('#captchaWrap');if(!key){if(window.APP_CONFIG?.REQUIRE_CAPTCHA){$('#setupWarning').classList.remove('hidden');$('#setupWarning').textContent='Для входа требуется CAPTCHA. Укажите CAPTCHA_SITE_KEY в assets/js/config.js.';$('#loginForm button').disabled=true}return}wrap.classList.remove('hidden');const draw=()=>{if(!window.turnstile)return setTimeout(draw,150);captchaWidgetId=window.turnstile.render('#captchaWidget',{sitekey:key,callback:t=>captchaToken=t,'expired-callback':()=>captchaToken='','error-callback':()=>captchaToken=''})};draw()}

  function showPanel(name){$$('#adminNav button').forEach(b=>b.classList.toggle('active',b.dataset.panel===name));$$('.panel').forEach(p=>p.classList.toggle('active',p.id===`panel-${name}`));({general:renderGeneral,directions:renderDirections,about:renderAbout,contacts:renderContacts,design:renderDesign,stats:renderStats}[name])()}
  async function save(){try{$('#saveBtn').disabled=true;await SiteBackend.saveContent(data);clean();toast('Изменения опубликованы')}catch(e){toast('Ошибка сохранения: '+e.message)}finally{$('#saveBtn').disabled=false}}
  async function login(e){e.preventDefault();$('#loginError').textContent='';if(lockRemaining()>0){updateLoginGuard();return}if(window.APP_CONFIG?.REQUIRE_CAPTCHA&&!captchaToken){$('#loginError').textContent='Подтвердите CAPTCHA.';return}const button=$('#loginForm button[type="submit"]');button.disabled=true;try{const {error}=await SiteBackend.login($('#password').value,captchaToken);if(error)throw error;const ok=await SiteBackend.isAdmin();if(!ok){await SiteBackend.logout();throw new Error('access_denied')}clearLoginGuard();await SiteBackend.recordSecurityEvent('login_success');await enter()}catch(err){await SiteBackend.recordSecurityEvent('login_failed');registerLoginFailure();resetCaptcha();$('#loginError').textContent='Неверный пароль или вход временно заблокирован.'}finally{if(lockRemaining()===0)button.disabled=false}}
  async function enter(){const s=await SiteBackend.session();if(!s)return;if(!await SiteBackend.isAdmin()){await SiteBackend.logout();$('#loginError').textContent='Доступ запрещён.';return}$('#loginScreen').classList.add('hidden');$('#adminApp').classList.remove('hidden');const res=await SiteBackend.getContent();data=deepMerge(window.DEFAULT_SITE_CONTENT,res.data||{});$('#adminLoading').classList.add('hidden');$('#panel-general').classList.add('active');$('#savebar').classList.remove('hidden');clean();showPanel('general')}
  async function init(){updateLoginGuard();if(lockRemaining()>0&&!lockTimer)lockTimer=setInterval(updateLoginGuard,1000);initCaptcha();if(!SiteBackend.configured){$('#setupWarning').classList.remove('hidden');$('#loginForm button').disabled=true;return}$('#loginForm').onsubmit=login;$('#logoutBtn').onclick=async()=>{await SiteBackend.logout();location.reload()};$('#saveBtn').onclick=save;$$('#adminNav button').forEach(b=>b.onclick=()=>showPanel(b.dataset.panel));if(await SiteBackend.session())await enter();window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}})}
  document.addEventListener('DOMContentLoaded',init,{once:true});
})();
